# Generated by Django 3.0.4 on 2020-03-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clothes_clothesset_clothessetreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='lower_category',
            field=models.CharField(choices=[('blazer', 'blazer'), ('blouse', 'blouse'), ('blue_jacket', 'blue_jacket'), ('coach_jacket', 'coach_jacket'), ('coat', 'coat'), ('field_jacket', 'field_jacket'), ('golden_pants', 'golden_pants'), ('hoodie', 'hoodie'), ('hot_pants', 'hot_pants'), ('jeans', 'jeans'), ('leather_jacket', 'leather_jacket'), ('long_padding', 'long_padding'), ('long_skirt', 'long_skirt'), ('long_sleeve', 'long_sleeve'), ('long_sleeve_shirt', 'long_sleeve_shirt'), ('mustang', 'mustang'), ('short_padding', 'short_padding'), ('short_sleeve', 'short_sleeve'), ('short_sleeve_shirt', 'short_sleeve_shirt'), ('shorts', 'shorts'), ('skirt', 'skirt'), ('slacks', 'slacks'), ('stadium_jacket', 'stadium_jacket'), ('sweater', 'sweater'), ('sweatpants', 'sweatpants'), ('sweatshirt', 'sweatshirt'), ('track_top', 'track_top'), ('turtleneck', 'turtleneck'), ('vest_padding', 'vest_padding'), ('windbreaker', 'windbreaker')], max_length=30),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='upper_category',
            field=models.CharField(choices=[('bottom', 'bottom'), ('dress', 'dress'), ('outer', 'outer'), ('skirt', 'skirt'), ('top', 'top')], max_length=30),
        ),
        migrations.AlterField(
            model_name='clothessetreview',
            name='location',
            field=models.CharField(choices=[('cheonan', 'cheonan'), ('busan', 'busan'), ('seoul', 'seoul')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clothessetreview',
            name='review',
            field=models.CharField(choices=[('cold', 'cold'), ('cool', 'cool'), ('hot', 'hot'), ('warm', 'warm')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(True, 'man'), (False, 'woman')], null=True),
        ),
    ]
