# Generated by Django 3.0.4 on 2020-03-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200321_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(True, 'man'), (False, 'woman')], default=True),
        ),
    ]
