# Generated by Django 3.0.4 on 2020-03-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200322_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesset',
            name='style',
            field=models.CharField(choices=[('simple', 'simple'), ('street', 'street'), ('suit', 'suit'), ('date', 'date'), ('splendor', 'splendor')], max_length=30, null=True),
        ),
    ]
