# Generated by Django 3.0.4 on 2020-03-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200322_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='lower_category',
            field=models.CharField(choices=[('short_sleeve', 'short_sleeve'), ('long_sleeve', 'long_sleeve'), ('short_sleeve_shirt', 'short_sleeve_shirt'), ('long_sleeve_shirt', 'long_sleeve_shirt'), ('sweatshirt', 'sweatshirt'), ('turtleneck', 'turtleneck'), ('hoodie', 'hoodie'), ('sweater', 'sweater'), ('blouse', 'blouse'), ('spaghetti_strap', 'spaghetti_strap'), ('sleeveless', 'sleeveless'), ('shorts', 'shorts'), ('hot_pants', 'hot_pants'), ('slacks', 'slacks'), ('jeans', 'jeans'), ('golden_pants', 'golden_pants'), ('sweatpants', 'sweatpants'), ('skirt', 'skirt'), ('long_skirt', 'long_skirt'), ('blazer', 'blazer'), ('short_padding', 'short_padding'), ('vest_padding', 'vest_padding'), ('long_padding', 'long_padding'), ('stadium_jacket', 'stadium_jacket'), ('coach_jacket', 'coach_jacket'), ('windbreaker', 'windbreaker'), ('field_jacket', 'field_jacket'), ('mustang', 'mustang'), ('coat', 'coat'), ('track_top', 'track_top'), ('leather_jacket', 'leather_jacket'), ('blue_jacket', 'blue_jacket'), ('cardigan', 'cardigan'), ('dress', 'dress')], max_length=30),
        ),
    ]
