# Generated by Django 3.0.4 on 2020-04-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200326_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='lower_category',
            field=models.CharField(choices=[('반팔티셔츠', '반팔티셔츠'), ('긴팔티셔츠', '긴팔티셔츠'), ('반팔셔츠', '반팔셔츠'), ('긴팔셔츠', '긴팔셔츠'), ('맨투맨', '맨투맨'), ('터틀넥', '터틀넥'), ('후드티', '후드티'), ('니트', '니트'), ('블라우스', '블라우스'), ('끈나시', '끈나시'), ('민소매', '민소매'), ('반바지', '반바지'), ('핫팬츠', '핫팬츠'), ('슬랙스', '슬랙스'), ('청바지', '청바지'), ('골덴바지', '골덴바지'), ('트레이닝바지', '트레이닝바지'), ('미니스커트', '미니스커트'), ('롱스커트', '롱스커트'), ('블레이져', '블레이져'), ('숏패딩', '숏패딩'), ('조끼패딩', '조끼패딩'), ('롱패딩', '롱패딩'), ('야구점퍼', '야구점퍼'), ('항공점퍼', '항공점퍼'), ('바람막이', '바람막이'), ('야상', '야상'), ('무스탕', '무스탕'), ('코트', '코트'), ('트랙탑', '트랙탑'), ('가죽자켓', '가죽자켓'), ('청자켓', '청자켓'), ('가디건', '가디건'), ('원피스', '원피스')], max_length=30),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='upper_category',
            field=models.CharField(choices=[('하의', '하의'), ('원피스', '원피스'), ('아우터', '아우터'), ('치마', '치마'), ('상의', '상의')], max_length=30),
        ),
        migrations.AlterField(
            model_name='clothesset',
            name='style',
            field=models.CharField(choices=[('심플', '심플'), ('스트릿', '스트릿'), ('정장', '정장'), ('데이트', '데이트'), ('화려', '화려')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clothessetreview',
            name='review',
            field=models.IntegerField(choices=[(1, '춥다'), (2, '조금춥다'), (3, '좋다'), (4, '조금덥다'), (5, '덥다')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자')], default='성별을 입력해주세요.', max_length=2),
        ),
    ]
