# Generated by Django 3.0.4 on 2020-04-24 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='max_sensible_temp',
            new_name='sensible_temp',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='max_temp',
            new_name='temp',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='min_sensible_temp',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='min_temp',
        ),
    ]
