# Generated by Django 3.0.4 on 2020-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200424_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
