# Generated by Django 3.0.4 on 2020-04-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200428_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothessetreview',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='clothessetreview',
            name='precipitation',
            field=models.FloatField(),
        ),
    ]
