# Generated by Django 3.0.4 on 2020-05-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200430_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='precipitation',
            field=models.FloatField(),
        ),
    ]
