# Generated by Django 3.0.7 on 2020-08-03 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_reviewsensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsensor',
            name='location_code',
        ),
    ]
